### ISSUE TITLE
PiP mode does not updated when the participants changed

### ISSUE THREAD

**Issue by basarane** [coloquium/kollokvium#13]
When a new participant is added or removed from the meeting, the picture-in-picture (PiP) window is not updated correspondingly.

**Comment by MagnusThor** [comment]
Working on that + the fact the the aspect-ratio is/was wrong if remote-video was portrait.    Will be fixed wen we update mediablender.    C

**Comment by MagnusThor** [comment]
@basarane  PiP now refresh when active and participants, enter and leave.   In dev, and deployed in text merge.
