### ISSUE TITLE
Front camera not working on chrome cellphone

### ISSUE THREAD

**Issue by alfredosantos** [coloquium/kollokvium#14]
Hi, I'm testing the app and founded that front camera is not working in my Chrome cellphone.

**Comment by MagnusThor** [comment]
@alfredosantos thanks,  this "should be" fixed, you can try and help us validate on https://dev-wss.kollokvium.net/  and see if our latest fix does the trick.

Thanks for posting feedback

Magnus

**Comment by alfredosantos** [comment]
Hello, @MagnusThor, thanks for replying.
I did a test here and it didn't work.
To work I made a paleative: https://github.com/alfredosantos/kollokvium/commit/47c98af71a134d65045da129ae2d0096e4421093

**Comment by MagnusThor** [comment]
@alfredosantos fixed, thanks fot the tip, it's something that seems to pass my mind...  `shouldFaceUser` is now set to true on initial call to `defaultConstraints` .  

I know @tibor19 worked and fixed a few things in the settinds ( see cog icon ) , there you can select cameras etc.

**Comment by MagnusThor** [comment]
@alfredosantos Thanks btw for making me aware :-)

**Comment by MagnusThor** [comment]
> @alfredosantos fixed, thanks fot the tip, it's something that seems to pass my mind... `shouldFaceUser` is now set to true on initial call to `defaultConstraints` .
> 
> I know @tibor19 worked and fixed a few things in the settinds ( see cog icon ) , there you can select cameras etc.

Pushed to dev & master so kollokvium.se shoud be updated any time .

**Comment by alfredosantos** [comment]
Hi @MagnusThor now works it.

Thank you a lot.

Question for you.
1 - How many users can we have in a session?
2 - Can I contribute to the project with you?

**Comment by MagnusThor** [comment]
@alfredosantos as its pure p2p, i would say, 12 people , depending n the resolution etc.  bur with a limited resolution such as 360p , 12 is would be okey, on  desktop then.. 

And yes, welcome to contribute , post ideas, make pull requets etc.

**Comment by alfredosantos** [comment]
Nice @MagnusThor thank you!!!
