### ISSUE TITLE
GUM seem to fail on iOS/OSX Safari 

### ISSUE THREAD

**Issue by MagnusThor** [coloquium/kollokvium#15]
Seems like suddenly getUserMedia now fails on Safari both iOS and OSX .

Reason may be `facingMode`    I added some logging, dumping Err and supported constraints if it fails,  happy if we can test, and post the results , here.

**Comment by chrismatthieu** [comment]
@MagnusThor added on error, try again using fail safe mode automatically.

I verified that that it's now working on Mac/Safari and iOS flawlessly. 

Thank you!!!
