### ISSUE TITLE
Website fails on https and also does not work on ip address.

### ISSUE THREAD

**Issue by Teja-sai-08** [coloquium/kollokvium#17]
The static site which when I try to open on my localhost, works without any hiccups but it is under http only so no camera accessibility or mic. Whereas when I try to use my ip address, it seemingly crashes on loading into https and never reloads at all. Is it only with me? I followed the steps which are provided in the documentation  for installation.

**Comment by MagnusThor** [comment]
@Teja-sai-08 

Just run `npm start`  and navigate to http://localhost:1337 unless you dont have `process.env` set up .

localhost should not give you probelms accessig camera etc .

you can also run `npm run start:secure` , that fires an https:// host on local using the self-signed certs,  in this case server is started on port 4433 (see server.ts) , then navigate to https://localhost:4433/  or https://your-ip::4433/

**Comment by MagnusThor** [comment]
@Teja-sai-08 as no comment from you , i'm closing this isssue (question ) as i concider it working, as described above.
