### ISSUE TITLE
ActiveSpeaker view

### ISSUE THREAD

**Issue by MagnusThor** [coloquium/kollokvium#18]
Implement **active speaker** view ( @basarane   as dicuessed  5/6 ) .   

User can toggles between the the current , grid. Active speaker covers 60% of view height ( container ) , each participants shown as tiles underneath the activespaker element , each title has a maximum width & max height of 360p / 2 = 180px .  tiles starts in center, and the scales within one single row.    As we spoke, we reuse the current html,  and applies an additional class (`.active-speaker-view`) , as well as `.active-speaker` on the tile that is the acitive.

**Comment by basarane** [comment]
I created a gist to test and review. 
https://gist.github.com/basarane/182227aead7bd438d53ef6c644489468

Using the test html page, you can change the active speaker by clicking on the speakers. 

All new rules start with `.video-grid.speaker-view` selector. The CSS class `is-speaking` should be to be added to the `li` tag of the active speaker. Unfortunately two lines of JavaScript needs to be called after changing the active speaker. This is just for the case when the active speaker is the last in the list. It adds `pseudo-last-child` class to the last element that is not the active speaker. I couldn't find a way to do this using pure CSS.

**Comment by MagnusThor** [comment]
Great, i have tested the code of yours, and probably its gonna be shipped in next release.  If i run into any problems, i'll ping you @basarane  . Thanks for a great work.

**Comment by basarane** [comment]
With the addition of the following rules, the update is now pure CSS. No JS is needed. I updated the gist accordingly. 

```
.video-grid.speaker-view ul li:last-child {
  margin-right: auto !important;
}
.video-grid.speaker-view ul li:nth-last-child(2) {
  margin-right: auto;
}
.video-grid.speaker-view ul li.is-speaking ~ li {
  margin-right: 0;
}

```

**Comment by MagnusThor** [comment]
@basarane  Now on dev, needs proper testing - https://dev-wss.kollokvium.net/  (  hotket ctrl-g / command-g ) , or use the meny top and toggle grid.. 

Made some minor adjustemets z-index, and some margins , great work mate!

**Comment by MagnusThor** [comment]
Closeing the issue for now.
