### ISSUE TITLE
Devices connected to same room URL don't 'see each other'.

### ISSUE THREAD

**Issue by jonathanhinterberger** [coloquium/kollokvium#26]
This happens frequently for me. I'm in the USA testing multiple devices (Mac, Windows, iPhone, Android) all via Chrome on my wifi.

Essentially it appears to each device connected that they are the only one in the room.

Suggestions for how to troubleshoot are welcome.

**Comment by MagnusThor** [comment]
Hi @jonathanhinterberger , thanks for the report, it's similar to the one reported by earlier.   Been doing inter contnentals tests ,  Sweden , England,  Turkey and USA ( Arizona ) recently with a successfull result.  But the error you reported is urgen to solve, so i'm on that right now. 

I have a few more questions in this matter that i would likte you to answer.

1.  Does the error / bug occur when randomly, lets say you start a room and then connect  more devices?  Does it drop connect and drop after a while?

2.As you are on wifi, its really strange if it drops..  Do you the poster ( no camera image ) , that poster should be visible if a proper peerconnection is established.

3.  Its hard for us to arrange tests, the error reported cannot be reprocuced, but i guess thats can be related to my setup of devices.  So can we arrange a time/date for us fo do a test.

When you run into this error , you can press `ctrl+u`to generate a log that is very useful for me, please do so, if possible. 

Again, thanks for your valuable feedback Jonathan.

**Comment by jonathanhinterberger** [comment]
Hi @MagnusThor. Here is what I've found so far:

1. I haven't had issues with dropped connections, but I have yet not tested for longevity.
2. The issue I'm talking about here is what appears to be no peer connection.
3. Happy to arrange a time if I can help. I am in US EST (right now it's 11:07am my time.)

I've run some tests today and come across a few small bugs which I'll open other issues for, but haven't reproduced the issue we've been discussing here again yet.

When I press ctrl+u does that generate a log on your server with no alert on my device? That's fine I suppose, I simply don't know if if is being created.

**Comment by MagnusThor** [comment]
Great! @jonathanhinterberger  thanks for giving kollokvium some time..   

I have been doing some changes, to the RTCPeerConnections  (thor-io.client)  that i do belive will improve the connectivity as well as the media streams the is lost sometimes.  this is now deployed for test , both at dev and https://kollokvium.se 

The problem with "Devices connected to same room URL don't 'see each other' "  is new,  do you mean that they dont seem so appear in the same room ?  Interesting thou..

Regarding `ctrl+u` the application should fire  back 1-n files for download ( to your client ) , nothing is sent back to the server (or me)  , make sure you have the window focues when pressing ctrl-u ,  just click somewhere in browser .

I'm this week a bit off and busy, but maybe we can try to talk on kollkvium some day?

regards

Magnus

**Comment by MagnusThor** [comment]
@jonathanhinterberger can we elaborate on this?

**Comment by MagnusThor** [comment]
Closing this issue now,  can reopnen if needed.
