### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by vikashkachhawa** [coloquium/kollokvium#32]
Error during WebSocket handshake: Unexpected response code: 200 
when code uploaded to the hostgator vps

**Comment by MagnusThor** [comment]
@vikashkachhawa  sorry for a late answer, but xmas and holidays came in between.   Yes,  as its seems the websocket is not set up properly.   I have no experience of "hostgator vps" so i need logs to be able to see, such as the Request information from the Chrome "Nework" and the tab WS tab,

Maybe you already solved it?  Let ne know then how .  

Kind redgards 

Magnus Thor
