### ISSUE TITLE
Breakout & beam to grouproom.io

### ISSUE THREAD

**Issue by MagnusThor** [coloquium/kollokvium#33]
The idea is from a kollokvium session enable users the possibillity to breakout / beam into an a new or ongoing grouproom.io meeting.  Myabe @chrismatthieu have drop a few lines ideas ?

**Comment by chrismatthieu** [comment]
We have recently added "Zoom" integration to GroupRoom (https://medium.com/grouproom/zoom-integration-685363fd38f0). This feature will actually work with any web based meeting platform such as Kollokvium.

The idea is that users can hangout in GroupRoom before a meeting and be automatically redirected to the meeting when it starts by passing in the meeting url and start time as query parameters into GroupRoom. 

It would be *really* cool if the Kollokvium could redirect users back to GroupRoom after the meeting. Perhaps this could be done by checking the referrrer of the initial request. If rerferror === 'grouproom.io' redirect. Open to discussion and suggestions.

**Comment by MagnusThor** [comment]
@chrismatthieu is see a solution that allows users from i.e kollo do  breakout to a room in GroupRoom,  how we do it ? using referers, or API calls, to set up and autojoin?

I more see, the "integration" in a way , that "proper" meetings / gatherings , can he held on GroupRoom.   Coworking and smaller meetings works fine in a traditinal platform, but if we have gatherings, and vitrtual office spaces,  

Maybe we need to think outside the box ?

**Comment by MagnusThor** [comment]
The beam idea, i can explain futher, we may need a session online regaring this,  Beam is just very breif description  :)
