### ISSUE TITLE
builds

### ISSUE THREAD

**Issue by MagnusThor** [coloquium/kollokvium#52]
@tibor19 did a push, seems like deploy from master fails?   Got a few updates comming .  can you have a look ?

**Comment by MagnusThor** [comment]
Seems like 1.8.2 is now in place, is there anything i need to consider when i do a push, @tibor19  .

**Comment by tibor19** [comment]
@MagnusThor I fixed that, can you confirm

**Comment by MagnusThor** [comment]
Yes, seems like builds works, was a big delay.but the two last commits / builds worked fine.
