### ISSUE TITLE
Add keybord shortcuts (hotkeys)

### ISSUE THREAD

**Issue by MagnusThor** [coloquium/kollokvium#8]
We need to add keybord shortcuts i.e for mute camera / video , speakers . 

Do think we can rely on this library, seems capable , and works on different OS, browers etc.

https://github.com/jaywcjlove/hotkeys

**Comment by MagnusThor** [comment]
@kaista82 , i think @basarane can assist in this...

**Comment by MagnusThor** [comment]
ctrl-F - Togggle fullscreen
ctrl-M - Mute or unmute your microphone
ctrl-V - Start or stop your camera
ctrl-I - Open or close the chat
ctrl-S - Toggle Captions
ctrl-R - Toggle Record
ctrl-T - Toggle speakers (mute/unmute)
1-9 - fullscreen view of remote vider

**Comment by MagnusThor** [comment]
@kaista82 been giving it a few mins, i noticed the hotkeys, add;

how about;

 ```
     <div class="p-3">
                <i class="fas fa-video fa-2x" id="mute-local-video" data-hotkey="ctrl+v"></i>
            </div>
            <div class="p-3">
                <i class="fas fa-microphone fa-2x" id="mute-local-audio" data-hotkey="ctrl+m"></i>
            </div>
```


then pasre for all `<elements>` with the data-hotkey, and bind the "click" event , that way we can just delcare "hotkeys" on elements?    Maybe , also do a` data-hotkey-trigger`   attribute?

**Comment by kaista82** [comment]
I like the idea!

**Comment by MagnusThor** [comment]
data-hotkey="..."  should do the trick now

**Comment by MagnusThor** [comment]
@kaista82 add the keys + if yuou figure more out an commit, and close this issue..  1.9 may be moved to a new issue?

**Comment by MagnusThor** [comment]
@kaista82 do we have a clue about fullscreen.toggle , or do we just use th enew active speaker view? Maybe if in active speaker + fullscreen automaticly swap srcObj ( stream)  ?

**Comment by MagnusThor** [comment]
Closinging this issue.
