### ISSUE TITLE
Mute all Option to Host/Participants  list/who is the Host/Name of the participants

### ISSUE THREAD

**Issue by sachinbhatt1** [coloquium/kollokvium#9]
1) how we can give Mute All option to the host only.
 2) how to identify who is the host of the meeting.
 3) How to See participants  list
4) Can we see the participant's name below video streaming?

**Comment by MagnusThor** [comment]
Quick answers

1. I guess you are thinking of muting all video/audio ?    But please futher describe what are refering to as host.

2 . I don't see the point in such function?  But of coz,  The one that is the first participant,  can be classified as creator ( host? )

3. @kaista82 as been dropping the same idea, so we may see such a participant list.   But one of our main "goals" has been t keep it as simple as possbile. 

4. Yes , it possible, and if we do the participant list)  , this may be agood idea )

**Comment by MagnusThor** [comment]
Planned , see readme.md
